repos:
  - repo: local
    hooks:
    # - id: isort
    #   name: isort
    #   entry: poetry run isort .
    #   language: system
    #   types: [python]

    - id: black
      name: black
      entry: poetry run black .
      language: system
      types: [python]

    - id: ruff
      name: ruff
      entry: poetry run ruff --fix .
      language: system
      types: [python]

    # TODO: make this work
    # - id: mypy
    #   name: mypy
    #   entry: poetry run mypy .
    #   language: system
    #   types: [python]

